// user auth
export const GET_USER_AUTH = "GET_USER_AUTH";
export const EDIT_USER_AUTH_INFO_PSEUDO = "EDIT_USER_AUTH_INFO_PSEUDO";
export const EDIT_USER_AUTH_INFO_NOM = "EDIT_USER_AUTH_INFO_NOM";
export const EDIT_USER_AUTH_INFO_PRENOM = "EDIT_USER_AUTH_INFO_PRENOM";
export const EDIT_USER_AUTH_INFO_EMAIL = "EDIT_USER_AUTH_INFO_EMAIL";
export const EDIT_USER_AUTH_INFO_BIRTHDAY = "EDIT_USER_AUTH_INFO_BIRTHDAY";
export const EDIT_USER_AUTH_INFO_COUNTRY = "EDIT_USER_AUTH_INFO_COUNTRY";
export const EDIT_USER_AUTH_INFO_BIO = "EDIT_USER_AUTH_INFO_BIO";
export const SUGGESTION_FRIEND = "SUGGESTION_FRIEND";
export const SEND_INVITATION = "SEND_INVITATION";
export const SEND_INVITATION_ABORT = "SEND_INVITATION_ABORT";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
export const REFUSE_INVITATION = "REFUSE_INVITATION";
export const DELETE_FRIEND_USER_AUTH = "DELETE_FRIEND_USER_AUTH";

// all users
export const GET_ALL_USERS = "GET_ALL_USERS";

// user
export const GET_USER = "GET_USER";
export const EDIT_USER_INFO_PSEUDO = "EDIT_USER_INFO_PSEUDO";
export const EDIT_USER_INFO_NOM = "EDIT_USER_INFO_NOM";
export const EDIT_USER_INFO_PRENOM = "EDIT_USER_INFO_PRENOM";
export const EDIT_USER_INFO_EMAIL = "EDIT_USER_INFO_EMAIL";
export const EDIT_USER_INFO_BIRTHDAY = "EDIT_USER_INFO_BIRTHDAY";
export const EDIT_USER_INFO_COUNTRY = "EDIT_USER_INFO_COUNTRY";
export const EDIT_USER_INFO_BIO = "EDIT_USER_INFO_BIO";
export const EDIT_USER_INFO_PICTURE = "EDIT_USER_INFO_PICTURE";
export const EDIT_USER_INFO_BG_PICTURE = "EDIT_USER_INFO_BG_PICTURE";
export const DELETE_FRIEND = "DELETE_FRIEND";

// all posts
export const GET_ALL_POSTS = "GET_ALL_POSTS";

// post
export const CREATE_POST_NO_IMG = "CREATE_POST_NO_IMG";
export const CREATE_POST_WITH_IMG = "CREATE_POST_WITH_IMG";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";
export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";

// comment
export const COMMENT_POST = "COMMENT_POST";
export const EDIT_COMMEMNT_POST = "EDIT_COMMEMNT_POST";
export const DELETE_COMMEMNT_POST = "DELETE_COMMEMNT_POST";
export const LIKE_COMMENT_POST = "LIKE_COMMENT_POST";
export const DISLIKE_COMMENT_POST = "DISLIKE_COMMENT_POST";

// messagerie
export const MY_FRIEND_DISCUSSION = "MY_FRIEND_DISCUSSION";
export const CREATE_NEW_FRIEND_DISCUSSION = "CREATE_NEW_FRIEND_DISCUSSION";
export const GET_DISCUSSION_WITH_FRIEND = "GET_DISCUSSION_WITH_FRIEND";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const LIVE_MESSAGE = "LIVE_MESSAGE";
